# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:

- main



pool:

  name: Default



stages:

# -------------------- BUILD --------------------

- stage: Build

  displayName: Build DACPAC

  jobs:

  - job: Build

    steps:

    - checkout: self

      persistCredentials: true

      clean: true



    # 用 sqlproj 来 build，避免找不到 sln

    - task: MSBuild@1

      displayName: Build SSDT sqlproj

      inputs:

        solution: 'src/**/Database*.sqlproj'



        msbuildArguments: '/p:Configuration=Debug'



    # 把 dacpac 收集进 artifact

    - task: CopyFiles@2

      displayName: Copy dacpac to staging

      inputs:

        SourceFolder: '$(Build.SourcesDirectory)'

        Contents: '**/*.dacpac'

        TargetFolder: '$(Build.ArtifactStagingDirectory)'



    - task: PublishBuildArtifacts@1

      displayName: Publish artifact

      inputs:

        PathtoPublish: '$(Build.ArtifactStagingDirectory)'

        ArtifactName: 'drop'

        publishLocation: 'Container'





# -------------------- DEPLOY DEV --------------------

- stage: Deploy_DEV

  displayName: Deploy to DEV

  dependsOn: Build

  variables:

  - group: Dev-Group   # 这里名字要和 Library 完全一致

  jobs:

  - job: DeployDEV

    steps:

    - download: current

      artifact: drop



    - task: SqlDacpacDeploymentOnMachineGroup@0

      displayName: Deploy DACPAC to DEV

      inputs:

        TaskType: 'dacpac'

        DacpacFile: '$(Pipeline.Workspace)/drop/**/gold_tempo.dacpac'

        TargetMethod: 'server'

        ServerName: '$(DEV_SQL_SERVER)'

        DatabaseName: '$(DEV_DB_NAME)'

        AuthScheme: 'sqlServerAuthentication'

        SqlUsername: '$(DEV_DB_USER)'

        SqlPassword: '$(DEV_DB_PASSWORD)'





# -------------------- DEPLOY PROD --------------------

- stage: Deploy_PROD

  displayName: Deploy to PROD

  dependsOn: Build

  variables:

  - group: Prod_Group  # 这里也要完全一致

  jobs:

  - job: DeployPROD

    steps:

    - download: current

      artifact: drop



    - task: SqlDacpacDeploymentOnMachineGroup@0

      displayName: Deploy DACPAC to PROD

      inputs:

        TaskType: 'dacpac'

        DacpacFile: '$(Pipeline.Workspace)/drop/**/gold_tempo.dacpac'

        TargetMethod: 'server'

        ServerName: '$(PROD_SQL_SERVER)'

        DatabaseName: '$(PROD_DB_NAME)'   # 你这里在 Prod_Group 里填 gold_copy

        AuthScheme: 'sqlServerAuthentication'

        SqlUsername: '$(PROD_DB_USER)'

        SqlPassword: '$(PROD_DB_PASSWORD)'